
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

trigger:
- CI/CD

pool:
  name: BODE-Development-IPZ




- task: Docker@1
  displayName: 'Build Docker Image'
  inputs:
    dockerRegistryEndpoint: 'Docker Hub'
    command : 'Build an image'
    dockerFile: '/Dockerfile'
    imageName: 'image1'
    

    
- script: |
    git --version
    git clone https://rb-devops.bosch.com/COL-CI_BODE/BODE/_git/BODE_Portal
    npm install
    npm run build
  displayName: 'npm install and build'
